### ISSUE TITLE
三栏布局

### ISSUE THREAD

**Issue by wss534857356** [wss534857356/notes#6]
三栏布局及类似固定加百分比布局
常用方案: 
```css
.div_left {
  float: left;
  width: 100px;
}
.div_center {
  margin: 0 100px;
}
.div_right {
  float: right;
  width: 100px;
}
```

//TODO: other project
